version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: gomod
    schedule:
      interval: weekly
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/*"
      valkey:
        patterns:
          - "github.com/valkey-io/*"

  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: docker
    schedule:
      interval: weekly
    
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: github-actions
    schedule:
      interval: weekly
